services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=DotnetDockerDB;Username=postgres;Password=postgres
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: DotnetDockerDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  front:
    build:
      context: ./Angular
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4200:8080"  
    depends_on:
      - api

volumes:
  postgres_data:
    driver: local
