services:
  api:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: devcontainer-api
    init: true
    working_dir: /workspace/api
    command: sleep infinity
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    volumes:
      - ./DotnetDockerAPI:/workspace/api:cached
      - dotnet-cache:/root/.nuget/packages
      
  front:
    image: node:20
    container_name: devcontainer-angular
    init: true
    working_dir: /workspace/front
    command: sleep infinity
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./Angular/mon-app-angular:/workspace/front:cached
      - node-cache:/workspace/front/node_modules
    depends_on:
      - api

volumes:
  dotnet-cache:
    driver: local
  node-cache:
    driver: local